version: '3'

networks:
  accounting:

services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounting
      MYSQL_USER: accounting
      MYSQL_PASSWORD: accounting
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - accounting

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - accounting
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "3000:8080"
    volumes:
      - ./accounting/static:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - accounting

  accounting:
    build:
      context: .
    command: >
      sh -c "poetry run python manage.py wait_for_db && \
             poetry run python manage.py migrate && \
             poetry run uwsgi --socket :8000 --ini Accounting_uwsgi.ini"
    env_file:
      - .env
    networks:
      - accounting
    depends_on:
      - mysql

