version: '3'

networks:
  accounting:

services:
  mysql:
    image: mysql:8.0.34
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounting
      MYSQL_USER: accounting
      MYSQL_PASSWORD: accounting
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - accounting

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - accounting
    depends_on:
      - mysql

  accounting:
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "poetry run python manage.py wait_for_db && \
             poetry run python manage.py migrate && \
             poetry run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    networks:
      - accounting
    depends_on:
      - mysql

