# Generated by Django 4.2.7 on 2023-12-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accounting_type_category_accounting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accounting',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
