# Generated by Django 4.2.7 on 2023-12-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_savemoneytarget_monthtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemoneytarget',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
