# Generated by Django 4.2.7 on 2023-12-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_savemoneytarget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemoneytarget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
